version: "3.5"

services:
  axonserver:
    image: axoniq/axonserver:2023.2.2-jdk-17
    container_name: eventstore-eclipsestore-axonserver
    ports:
      - "8024:8024"
      - "8124:8124"
    volumes:
      - .docker/config:/axonserver/config:ro
      - .docker/data:/axonserver/data
      - .docker/events:/axonserver/events

  postgres:
    image: postgres:13.2
    container_name: eventstore-eclipsestore-postgresql
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: eclipse-store
    ports:
      - '25432:5432'

