version: "3.5"

services:
  axonserver:
    image: axoniq/axonserver:2024.0.4-jdk-17
    container_name: eventstore-eclipsestore-axonserver
    ports:
      - "8024:8024"
      - "8124:8124"
    volumes:
      - .docker/config:/axonserver/config:ro
      - .docker/data:/axonserver/data
      - .docker/events:/axonserver/events

  postgres:
    image: postgres:16.3
    container_name: eventstore-eclipsestore-postgresql
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: eclipse-store
    volumes:
      - .docker/postgresql/lib:/var/lib/postgresql
      - .docker/postgresql/run:/var/run/postgresql
    ports:
      - '25432:5432'

