axoniq:
  axonserver:
    name: university-eclipse-store-local
    hostname: localhost
    standalone: true
    accesscontrol:
      enabled: false
    devmode:
      enabled: true
    event:
      segment-size: 1000000 # 1mb for small segments
    snapshot:
      segment-size: 1000000 # 1mb for small segments
