axoniq:
  axonserver:
    name: eventstore-transformations-local
    hostname: localhost
    standalone: true
    accesscontrol:
      enabled: false
    devmode:
      enabled: true
    event:
      segment-size: 1000000 # 1mb
    snapshot:
      segment-size: 1000000 # 1mb
