spring:
  application:
    name: axon-eclipse-store-projection-example

axon:
  serializer:
    events: jackson
    general: jackson
    messages: jackson

springdoc:
  enable-kotlin: true
  swagger-ui:
    try-it-out-enabled: true
    url: /v3/api-docs

server:
  port: 8091

org:
  eclipse:
    store:
      storage-directory: .storage/
      channel-count: 2

logging:
  level:
    io.holixon.example.axon.eclipsestore.infrastructure: INFO # set to DEBUG for Eclipse Store play.
