org:
  eclipse:
    store:
      rest:
        enabled: false
      auto-start: false
      storage-filesystem:
        sql:
          postgres:
            url: jdbc:postgresql://localhost:25432/eclipse-store
            user: user
            password: secret
            data-source-provider: io.holixon.example.university.global.support.eclipsestore.SpringSqlDataSourceProvider
            catalog: "public"
