org:
  eclipse:
    store:
      rest:
        enabled: false

vaadin:
  url-mapping: /storage-console/*

axon-projection-support:
  store-key: ${spring.application.name}
  instance-key: default
  store:
    auto-start: false
    auto-create-default-storage: false
    auto-create-default-foundation: false
    storage-directory: .storage/${axon-projection-support.instance-key}
    backup-directory: .backup/${axon-projection-support.instance-key}

