org:
  eclipse:
    store:
      rest:
        enabled: false
      auto-start: false
      storage-directory: .storage/default
      backup-directory: .backup/default
      auto-create-default-storage: false
      auto-create-default-foundation: false

